import type { Metadata } from "next";
// import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";

// const monteserrat = Montserrat({
//   variable: "--font-mont-sans",
//   subsets: ["latin"],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Infinte Change",
  description: "Generated by Badal Kumar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
